import { CloudCard } from '@/components/cards/cloud-card';
import { CreateCloudCard } from '@/components/cards/create-cloud-card';
import { requireSession } from '@/lib/utils';
import { SidebarProvider } from '@repo/ui/components/sidebar';
import * as API from '@repo/api-client';
import { headers } from 'next/headers';
import { CardGrid } from '@/components/containers/card-grid';
import Image from 'next/image';
import NoDataImage from '@public/graphics/no-data.svg';
import { Button } from '@repo/ui/components/button';
import Link from 'next/link';
import { PlusCircle } from 'lucide-react';

export default async function CloudsPage() {
  await requireSession();

  const response = await API.getClouds({
    headers: await headers()
  });

  const clouds = response.data.data;

  return clouds.length > 0 ? (
    <div className="flex flex-1 flex-col gap-4 p-4 pt-0">
      <CardGrid>
        <CreateCloudCard />
        {clouds.map((data) => (
          // @ts-expect-error: The fields are not undefined here. This is a bug in the code generated by orval.
          <CloudCard key={data.id} usedStorage={0} {...data} />
        ))}
      </CardGrid>
    </div>
  ) : (
    <div className="w-full h-full flex flex-col items-center justify-center gap-10 relative">
      <Image
        src={NoDataImage}
        alt="No data"
        className="max-w-3xs object-cover"
        // className="dark:brightness-[0.2] dark:grayscale"
        priority
      />
      <div className="flex flex-col items-center gap-4">
        <div className="flex flex-col items-center gap-1">
          <h1 className="text-3xl">No Clouds Found</h1>
          <h2 className="text-muted-foreground">Get started by creating a new cloud below</h2>
        </div>
        <Link href="/clouds/new">
          <Button>
            Create Cloud
            <PlusCircle />
          </Button>
        </Link>
      </div>
    </div>
  );
}
